apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cosmocloud-deploy.fullname" . }}
  labels:
    {{- include "cosmocloud-deploy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cosmocloud-deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cosmocloud-deploy.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: REDIS_URI
              value: {{ .Values.backend.env.REDIS_URI }}
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: BACKEND_URL
              value: {{ .Values.frontend.env.BACKEND_URL }}
        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: {{ .Values.redis.service.port }}
