{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmocloud-deploy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "{{ (index .Values.ingress.hosts 0).host | default "localhost" }}" # Correctly extract the host
      http:
        paths:
          - path: "{{ (index (index .Values.ingress.hosts 0).paths 0).path | default "/" }}" # Correctly extract the path
            pathType: "{{ (index (index .Values.ingress.hosts 0).paths 0).pathType | default "ImplementationSpecific" }}" # Correctly extract the pathType
            backend:
              service:
                name: frontend-svc
                port:
                  number: 5175
{{- end }}
