apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app.kubernetes.io/name: {{ include "cosmocloud-deploy.name" . }}
  ports:
    - port: 8000
      targetPort: 8000
  type: {{ .Values.backend.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app.kubernetes.io/name: {{ include "cosmocloud-deploy.name" . }}
  ports:
    - port: 5175
      nodePort: 31000
  type: {{ .Values.frontend.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app.kubernetes.io/name: {{ include "cosmocloud-deploy.name" . }}
  ports:
    - port: 6379
  type: {{ .Values.redis.service.type }}
