# Default values for cosmocloud-deploy.
replicaCount: 1

backend:
  image: shreybatra/sample-backend
  env:
    REDIS_URI: "redis://redis-svc:6379"
  service:
    type: ClusterIP
    port: 8000

frontend:
  image: shreybatra/sample-frontend
  env:
    BACKEND_URL: "http://backend-svc:8000"
  service:
    type: NodePort
    port: 5175
    nodePort: 31000

redis:
  image: redis
  service:
    type: ClusterIP
    port: 6379

# Image repository and pull settings
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

# Image pull secrets
imagePullSecrets: []

# Service Account Configuration
serviceAccount:
  create: true
  automount: true
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security context settings
podSecurityContext: {}
securityContext: {}

# Service settings
service:
  type: ClusterIP
  port: 80

# Ingress settings
ingress:
  enabled: true
  hosts:
    - host: "localhost"  # Using 'localhost' as the valid hostname for testing
      paths:
        - path: "/"
          pathType: ImplementationSpecific
  tls: []

# Resource allocation
resources: {}

# Liveness and Readiness probes
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Volumes and volume mounts
volumes: []
volumeMounts: []

# Node selector, tolerations, and affinity settings
nodeSelector: {}
tolerations: []
affinity: {}
